server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiracao=28800000

google.sheets.credenciais=${GOOGLE_CREDENTIALS_PATH}
google.sheets.id.anamnese=${SHEETS_ID_ANAMNESE}
google.sheets.id.agendamentos=${SHEETS_ID_AGENDAMENTOS}
google.sheets.id.avaliacoes=${SHEETS_ID_AVALIACOES}