server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiracao=28800000

google.sheets.credenciais=${GOOGLE_CREDENTIALS_PATH}
google.sheets.id=${SHEETS_ID}
google.sheets.anamnese.aba=ANAMNESE ALUNOS
google.sheets.anamnese.range=B7:H
google.sheets.agendamentos.manha.aba=AULAS MANHÃ
google.sheets.agendamentos.manha.range=B2:J
google.sheets.agendamentos.tarde.aba=AULAS TARDE/NOITE
google.sheets.agendamentos.tarde.range=B2:J
google.sheets.avaliacoes.aba=Avaliações
google.sheets.avaliacoes.range=B2:K